module.exports = [
  "TSA guidelines now prohibit $ANSWER on airplanes.",
  "It's a pity that kids these days are all getting involved with $ANSWER.",
  "In 1,000 years, when paper money is but a distant memory, $ANSWER will be our currency.",
  "Major League Baseball has banned $ANSWER for giving players an unfair advantage.",
  "What is Batman's guilty pleasure?",
  "Next from J.K. Rowling: Harry Potter and the Chamber of $ANSWER.",
  "I'm sorry, Professor, but I couldn't complete my homework because of $ANSWER.",
  "What did I bring back from Mexico?",
  "$ANSWER? There's an app for that.",
  "$ANSWER. Betcha can't have just one!",
  "What's my anti-drug?",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on $ANSWER.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with $ANSWER for the first time.",
  "What's my secret power?",
  "What's the new fad diet?",
  "What did Vin Diesel eat for dinner?",
  "When Pharaoh remained unmoved, Moses called down a Plague of $ANSWER.",
  "How am I maintaining my relationship status?",
  "What's the crustiest?",
  "In L.A. County Jail, word is you can trade 200 cigarettes for $ANSWER.",
  "After the earthquake, Sean Penn brought $ANSWER to the people of Haiti.",
  "Instead of coal, Santa now gives the bad children $ANSWER.",
  "Life for American Indians was forever changed when the White Man introduced them to $ANSWER.",
  "What's Teach for America using to inspire inner city students to succeed?",
  "Maybe she's born with it. Maybe it's $ANSWER.",
  "In Michael Jackson's final moments, he thought about $ANSWER.",
  "White people like $ANSWER.",
  "Why do I hurt all over?",
  "A romantic, candlelit dinner would be incomplete without $ANSWER.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "BILLY MAYS HERE FOR $ANSWER.",
  "The class field trip was completely ruined by $ANSWER.",
  "What's a girl's best friend?",
  "Dear Abby, I'm having some trouble with $ANSWER and would like your advice.",
  "When I am President of the United States, I will create the Department of $ANSWER.",
  "What are my parents hiding from me?",
  "What never fails to liven up the party?",
  "What gets better with age?",
  "$ANSWER: Good to the last drop.",
  "I got 99 problems but $ANSWER ain't one.",
  "$ANSWER. It's a trap!",
  "MTV's new reality show features eight washed-up celebrities living with $ANSWER.",
  "What would grandma find disturbing, yet oddly charming?",
  "What's the most emo?",
  "During sex, I like to think about $ANSWER.",
  "What ended my last relationship?",
  "What's that sound?",
  "$ANSWER. That's how I want to die.",
  "Why am I sticky?",
  "What's the next Happy Meal toy?",
  "What's there a ton of in heaven?",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with $ANSWER.",
  "What will always get you laid?",
  "$ANSWER: Kid-tested, mother-approved.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "What helps Obama unwind?",
  "This is the way the world ends / This is the way the world ends / Not with a bang but with $ANSWER.",
  "Coming to Broadway this season, $ANSWER: The Musical.",
  "Anthropologists have recently discovered a primitive tribe that worships $ANSWER.",
  "But before I kill you, Mr. Bond, I must show you $ANSWER.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to $ANSWER.",
  "Next on ESPN2: The World Series of $ANSWER.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate $ANSWER.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on $ANSWER.",
  "War! What is it good for?",
  "What gives me uncontrollable gas?",
  "What do old people smell like?",
  "What am I giving up for Lent?",
  "Alternative medicine is now embracing the curative powers of $ANSWER.",
  "What did the US airdrop to the children of Afghanistan?",
  "What does Dick Cheney prefer?",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of $ANSWER.",
  "What don't you want to find in your Chinese food?",
  "I drink to forget $ANSWER.",
  "$ANSWER. High five, bro.",
  "He who controls $ANSWER controls the world.",
  "The CIA now interrogates enemy agents by repeatedly subjecting them to $ANSWER.",
  "In Rome, there are whisperings that the Vatican has a secret room devoted to $ANSWER.",
  "Science will never explain the origin of $ANSWER.",
  "When all else fails, I can always masturbate to $ANSWER.",
  "I learned the hard way that you can't cheer up a grieving friend with $ANSWER.",
  "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated $ANSWER.",
  "The socialist governments of Scandinavia have declared that access to $ANSWER is a basic human right.",
  "In his new self-produced album, Kanye West raps over the sounds of $ANSWER.",
  "What's the gift that keeps on giving?",
  "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only $ANSWER and his wits.",
  "When I pooped, what came out of my butt?",
  "In the distant future, historians will agree that $ANSWER marked the beginning of America's decline.",
  "What has been making life difficult at the nudist colony?",
  "And I would have gotten away with it, too, if it hadn't been for $ANSWER.",
  "What brought the orgy to a grinding halt?",
  "$ANSWER. High five, bro.",
  "TSA guidelines now prohibit $ANSWER on airplanes.",
  "It's a pity that kids these days are all getting involved with $ANSWER.",
  "In 1,000 years, when paper money is but a distant memory, $ANSWER will be our currency.",
  "Major League Baseball has banned $ANSWER for giving players an unfair advantage.",
  "What is Batman's guilty pleasure?",
  "Next from J.K. Rowling: Harry Potter and the Chamber of $ANSWER.",
  "I'm sorry, Professor, but I couldn't complete my homework because of $ANSWER.",
  "What did I bring back from Mexico?",
  "$ANSWER? There's an app for that.",
  "Betcha can't have just one!",
  "What's my anti-drug?",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on $ANSWER.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with $ANSWER for the first time.",
  "What's my secret power?",
  "What's the new fad diet?",
  "What did Vin Diesel eat for dinner?",
  "When Pharaoh remained unmoved, Moses called down a Plague of $ANSWER.",
  "How am I maintaining my relationship status?",
  "What's the crustiest?",
  "When I'm in prison, I'll have $ANSWER smuggled in.",
  "After Hurricane Katrina, Sean Penn brought $ANSWER to the people of New Orleans.",
  "Instead of coal, Santa now gives the bad children $ANSWER.",
  "Life was difficult for cavemen before $ANSWER.",
  "What's Teach for America using to inspire inner city students to succeed?",
  "Who stole the cookies from the cookie jar?",
  "In Michael Jackson's final moments, he thought about $ANSWER.",
  "White people like $ANSWER.",
  "Why do I hurt all over?",
  "A romantic candlelit dinner would be incomplete without $ANSWER.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "BILLY MAYS HERE FOR $ANSWER.",
  "The class field trip was completely ruined by $ANSWER.",
  "What's a girl's best friend?",
  "I wish I hadn't lost the instruction manual for $ANSWER.",
  "When I am President of the United States, I will create the Department of $ANSWER.",
  "What are my parents hiding from me?",
  "What never fails to liven up the party?",
  "What gets better with age?",
  "$ANSWER: good to the last drop.",
  "I got 99 problems but $ANSWER ain't one.",
  "MTV's new reality show features eight washed-up celebrities living with $ANSWER.",
  "What would grandma find disturbing, yet oddly charming?",
  "What's the most emo?",
  "During sex, I like to think about $ANSWER.",
  "What ended my last relationship?",
  "What's that sound?",
  "$ANSWER. That's how I want to die.",
  "Why am I sticky?",
  "What's there a ton of in heaven?",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with $ANSWER.",
  "What will always get you laid?",
  "$ANSWER: kid tested, mother approved.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "What helps Obama unwind?",
  "This is the way the world ends \\ This is the way the world ends \\ Not with a bang but with $ANSWER.",
  "Coming to Broadway this season, $ANSWER: The Musical.",
  "Anthropologists have recently discovered a primitive tribe that worships $ANSWER.",
  "But before I kill you, Mr. Bond, I must show you $ANSWER.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to $ANSWER.",
  "Due to a PR fiasco, Walmart no longer offers $ANSWER.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate $ANSWER.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on $ANSWER.",
  "War! What is it good for?",
  "What gives me uncontrollable gas?",
  "What do old people smell like?",
  "Sorry everyone, I just $ANSWER.",
  "Alternative medicine is now embracing the curative powers of $ANSWER.",
  "The U.S. has begun airdropping $ANSWER to the children of Afghanistan.",
  "What does Dick Cheney prefer?",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of $ANSWER.",
  "What don't you want to find in your Chinese food?",
  "I drink to forget $ANSWER."
];
